import {
  Category,
  ChannelType,
  Customer,
  Product,
  PurchaseOrder,
  SalesOrder,
  StockLocation,
  Supplier,
} from '@/types';

export const initialChannelTypes: ChannelType[] = [
  { id: 'ct-1', name: 'Online', code: 'online', badge_variant: 'info', description: 'Canal de vendas digitais e e-commerce online', created_at: new Date().toISOString() },
  { id: 'ct-2', name: 'Depósito Interno / Matriz', code: 'internal', badge_variant: 'default', description: 'Armazém central e estoque pulmão da fábrica', created_at: new Date().toISOString() },
];

export const initialStockLocations: StockLocation[] = [
  {
    id: 'loc-1',
    name: 'Depósito Interno / Matriz',
    code: 'EST-MATRIZ',
    channel_type: 'internal',
    description: 'Armazém central e estoque matriz para produção e reposição',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loc-2',
    name: 'Estoque Online',
    code: 'EST-ONLINE',
    channel_type: 'online',
    description: 'Estoque reservado para expedição de vendas e pedidos online',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Perfumes Amadeirados', slug: 'amadeirados', description: 'Fragrâncias intensas com notas nobres de madeiras, cedro e sândalo', created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Perfumes Florais & Frutados', slug: 'florais-frutados', description: 'Composições florais radiantes com notas de jasmim, rosas e frutas nobres', created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Perfumes Cítricos & Frescos', slug: 'citricos-frescos', description: 'Fragrâncias leves e revigorantes com bergamota, mandarina e frescor aromático', created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Perfumes Orientais & Especiados', slug: 'orientais-especiados', description: 'Acordes quentes e sofisticados com âmbar, especiarias e fava tonka', created_at: new Date().toISOString() },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    corporate_name: 'Vidraria & Frascaria Premium Brasil Ltda',
    trade_name: 'Premium Glass Frascos',
    document: '12.345.678/0001-90',
    email: 'comercial@premiumglass.com.br',
    phone: '(11) 4002-8922',
    contact_person: 'Carlos Eduardo',
    notes: 'Fornecedor de frascos de vidro especial, válvulas spray luxo e tampas magnéticas',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sup-2',
    corporate_name: 'Essências Aromáticas & Óleos Nobres S.A.',
    trade_name: 'AromaNobre Essências',
    document: '98.765.432/0001-10',
    email: 'vendas@aromanobre.com.br',
    phone: '(11) 3210-9876',
    contact_person: 'Mariana Silveira',
    notes: 'Fornecedor de óleos essenciais importados de Grasse e álcool de cereais neutro',
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Ana Beatriz Souza',
    email: 'ana.beatriz@gmail.com',
    phone: '(11) 98765-4321',
    document: '345.678.901-22',
    document_type: 'CPF',
    status: 'active',
    notes: 'Cliente recorrente Shopee e Loja Física',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    addresses: [
      {
        id: 'addr-1',
        customer_id: 'cust-1',
        address_type: 'shipping',
        zip_code: '04571-010',
        street: 'Avenida Engenheiro Luís Carlos Berrini',
        number: '1000',
        complement: 'Apto 42',
        neighborhood: 'Brooklin',
        city: 'São Paulo',
        state: 'SP',
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'cust-2',
    name: 'Rodrigo Mendonça Santos',
    email: 'rodrigo.mendonca@outlook.com',
    phone: '(21) 99887-6655',
    document: '456.789.012-33',
    document_type: 'CPF',
    status: 'active',
    notes: 'Comprador frequente no Mercado Livre',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    addresses: [
      {
        id: 'addr-2',
        customer_id: 'cust-2',
        address_type: 'both',
        zip_code: '22041-001',
        street: 'Avenida Nossa Senhora de Copacabana',
        number: '550',
        complement: 'Bloco B Sala 301',
        neighborhood: 'Copacabana',
        city: 'Rio de Janeiro',
        state: 'RJ',
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'cust-3',
    name: 'Boutique & Perfumaria Elegance ME',
    email: 'compras@boutiqueelegance.com.br',
    phone: '(31) 3344-5566',
    document: '23.456.789/0001-88',
    document_type: 'CNPJ',
    status: 'active',
    notes: 'Revenda autorizada e cliente corporativo',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    addresses: [
      {
        id: 'addr-3',
        customer_id: 'cust-3',
        address_type: 'both',
        zip_code: '30130-110',
        street: 'Avenida Afonso Pena',
        number: '2000',
        complement: 'Andar 12',
        neighborhood: 'Funcionários',
        city: 'Belo Horizonte',
        state: 'MG',
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'NOCH-WOOD-100',
    barcode: '7898765430012',
    name: 'Perfume Nochelis Amadeirado Intenso EDP 100ml',
    description: 'Fragrância marcante e sofisticada com notas nobres de sândalo, cedro do atlas e âmbar negro. Fabricação própria Nochelis com fixação superior de mais de 12 horas.',
    category_id: 'cat-1',
    cost_price: 48.00,
    price: 249.90,
    min_price: 199.90,
    status: 'active',
    weight_kg: 0.380,
    width_cm: 8.0,
    height_cm: 15.0,
    length_cm: 8.0,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-1',
        product_id: 'prod-1',
        image_url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
        is_primary: true,
        display_order: 0,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-1-2',
        product_id: 'prod-1',
        image_url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
        is_primary: false,
        display_order: 1,
        created_at: new Date().toISOString(),
      },
    ],
    inventory: [
      { id: 'inv-1', product_id: 'prod-1', stock_location_id: 'loc-1', quantity: 95, reserved_quantity: 0, min_quantity_alert: 15, created_at: '', updated_at: '' },
      { id: 'inv-2', product_id: 'prod-1', stock_location_id: 'loc-2', quantity: 58, reserved_quantity: 2, min_quantity_alert: 10, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-2',
    sku: 'NOCH-FLOR-100',
    barcode: '7898765430029',
    name: 'Perfume Nochelis Fragrância A - Floral Radiante EDP 100ml',
    description: 'Assinatura floral refinada com acordes de jasmim de Grasse, lírio do vale e toques suaves de baunilha de Madagascar. Elaborado e produzido em nossos próprios laboratórios.',
    category_id: 'cat-2',
    cost_price: 42.00,
    price: 229.90,
    min_price: 189.90,
    status: 'active',
    weight_kg: 0.380,
    width_cm: 8.0,
    height_cm: 15.0,
    length_cm: 8.0,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-2',
        product_id: 'prod-2',
        image_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
        is_primary: true,
        display_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    inventory: [
      { id: 'inv-5', product_id: 'prod-2', stock_location_id: 'loc-1', quantity: 75, reserved_quantity: 0, min_quantity_alert: 12, created_at: '', updated_at: '' },
      { id: 'inv-6', product_id: 'prod-2', stock_location_id: 'loc-2', quantity: 45, reserved_quantity: 1, min_quantity_alert: 8, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-3',
    sku: 'NOCH-CITR-100',
    barcode: '7898765430036',
    name: 'Perfume Nochelis Cítrico & Fresco - Marine Breeze EDP 100ml',
    description: 'Explosão revigorante de notas cítricas com bergamota italiana, mandarina verde e fundo aromático fresco. Perfeito para o dia a dia e clima tropical.',
    category_id: 'cat-3',
    cost_price: 38.00,
    price: 199.90,
    min_price: 169.90,
    status: 'active',
    weight_kg: 0.380,
    width_cm: 8.0,
    height_cm: 15.0,
    length_cm: 8.0,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-3',
        product_id: 'prod-3',
        image_url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
        is_primary: true,
        display_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    inventory: [
      { id: 'inv-9', product_id: 'prod-3', stock_location_id: 'loc-1', quantity: 125, reserved_quantity: 0, min_quantity_alert: 15, created_at: '', updated_at: '' },
      { id: 'inv-10', product_id: 'prod-3', stock_location_id: 'loc-2', quantity: 77, reserved_quantity: 0, min_quantity_alert: 10, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-4',
    sku: 'NOCH-NOIR-100',
    barcode: '7898765430043',
    name: 'Perfume Nochelis Oriental Noir - Assinatura Especial EDP 100ml',
    description: 'Fragrância noturna misteriosa e sedutora com acordes de especiarias quentes, fava tonka, cardamomo e couro nobre. Uma obra de arte da perfumaria autoral Nochelis.',
    category_id: 'cat-4',
    cost_price: 55.00,
    price: 279.90,
    min_price: 229.90,
    status: 'active',
    weight_kg: 0.390,
    width_cm: 8.0,
    height_cm: 15.0,
    length_cm: 8.0,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: 'img-4',
        product_id: 'prod-4',
        image_url: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&q=80',
        is_primary: true,
        display_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    inventory: [
      { id: 'inv-13', product_id: 'prod-4', stock_location_id: 'loc-1', quantity: 55, reserved_quantity: 0, min_quantity_alert: 10, created_at: '', updated_at: '' },
      { id: 'inv-14', product_id: 'prod-4', stock_location_id: 'loc-2', quantity: 37, reserved_quantity: 0, min_quantity_alert: 5, created_at: '', updated_at: '' },
    ],
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-101',
    order_number: 'OP-2026-001',
    supplier_id: 'sup-1',
    destination_location_id: 'loc-1',
    status: 'received',
    total_amount: 4800.00,
    purchase_date: '2026-08-01',
    received_at: '2026-08-05T14:30:00Z',
    notes: 'Lote de produção própria - Perfume Nochelis Amadeirado Intenso.',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-05T14:30:00Z',
    items: [
      {
        id: 'poi-1',
        purchase_order_id: 'po-101',
        product_id: 'prod-1',
        quantity: 100,
        unit_cost_price: 48.00,
        subtotal: 4800.00,
      },
    ],
  },
  {
    id: 'po-102',
    order_number: 'OP-2026-002',
    supplier_id: 'sup-2',
    destination_location_id: 'loc-1',
    status: 'received',
    total_amount: 2750.00,
    purchase_date: '2026-08-08',
    received_at: '2026-08-12T09:15:00Z',
    notes: 'Lote de fabricação - Perfume Nochelis Oriental Noir.',
    created_at: '2026-08-08T08:00:00Z',
    updated_at: '2026-08-12T09:15:00Z',
    items: [
      {
        id: 'poi-2',
        purchase_order_id: 'po-102',
        product_id: 'prod-4',
        quantity: 50,
        unit_cost_price: 55.00,
        subtotal: 2750.00,
      },
    ],
  },
];

export const initialSalesOrders: SalesOrder[] = [
  {
    id: 'so-201',
    order_number: 'PED-ONL-8941',
    customer_id: 'cust-2',
    stock_location_id: 'loc-2', // Estoque Online
    status: 'delivered',
    subtotal: 499.80,
    discount: 0.00,
    shipping_fee: 0.00,
    total_amount: 499.80,
    total_cost: 96.00, // 2x Perfume Amadeirado custo 48
    gross_profit: 403.80, // 499.80 - 96.00 (80.7% margem)
    sale_date: new Date(Date.now() - 4 * 86400000).toISOString(),
    notes: 'Venda e-commerce online faturada e entregue.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    items: [
      {
        id: 'soi-1',
        sales_order_id: 'so-201',
        product_id: 'prod-1',
        quantity: 2,
        unit_sale_price: 249.90,
        unit_cost_price: 48.00,
        subtotal: 499.80,
        profit: 403.80,
      },
    ],
  },
  {
    id: 'so-202',
    order_number: 'PED-ONL-5520',
    customer_id: 'cust-1',
    stock_location_id: 'loc-2', // Estoque Online
    status: 'paid',
    subtotal: 229.90,
    discount: 15.00,
    shipping_fee: 0.00,
    total_amount: 214.90,
    total_cost: 42.00, // 1x Fragrância A Floral custo 42
    gross_profit: 172.90, // 214.90 - 42.00 (80.4% margem)
    sale_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: 'Campanha de lançamento loja virtual.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    items: [
      {
        id: 'soi-2',
        sales_order_id: 'so-202',
        product_id: 'prod-2',
        quantity: 1,
        unit_sale_price: 229.90,
        unit_cost_price: 42.00,
        subtotal: 229.90,
        profit: 187.90,
      },
    ],
  },
  {
    id: 'so-203',
    order_number: 'PED-MAT-1003',
    customer_id: 'cust-3',
    stock_location_id: 'loc-1', // Depósito Interno / Matriz
    status: 'paid',
    subtotal: 559.80,
    discount: 30.00,
    shipping_fee: 0.00,
    total_amount: 529.80,
    total_cost: 110.00, // 2x Oriental Noir (2x 55.00)
    gross_profit: 419.80, // 529.80 - 110.00 (79.2% margem)
    sale_date: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: 'Venda direta faturamento corporativo na Matriz.',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'soi-3',
        sales_order_id: 'so-203',
        product_id: 'prod-4',
        quantity: 2,
        unit_sale_price: 279.90,
        unit_cost_price: 55.00,
        subtotal: 559.80,
        profit: 449.80,
      },
    ],
  },
];
